Repository SWM-Cupid/jikting-backend, pull requests merged in 2023-08, with the labels that each got.

#140 [SP-251] 회원가입 요청 DTO 닉네임 추가
  src/main/java/com/cupid/jikting/member/dto/SignupRequest.java
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: fix

#138 [SP-156] Oauth2 적용 마무리
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/common/util/PasswordUtil.java
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/jwt/service/JwtService.java
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/entity/SocialType.java
  src/main/java/com/cupid/jikting/member/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/cupid/jikting/member/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/oauth2/CustomOAuth2User.java
  src/main/java/com/cupid/jikting/member/oauth2/OAuthAttributes.java
  src/main/java/com/cupid/jikting/member/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/cupid/jikting/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/cupid/jikting/member/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/cupid/jikting/member/repository/MemberRepository.java
  src/main/java/com/cupid/jikting/member/service/CustomOAuth2UserService.java
  src/main/resources/application.properties
Labels: feature

#144 [SP-253] 팀 등록 기능 한 팀 제한 로직 추가
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: feature, fix

#147 [SP-201] 회원 닉네임 수정 기능 구현
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#152 [SP-228] 호감 목록 조회 - 팀 상세 조회 구현
  src/main/java/com/cupid/jikting/like/controller/LikeController.java
  src/main/java/com/cupid/jikting/like/dto/MemberProfileResponse.java
  src/main/java/com/cupid/jikting/like/dto/TeamDetailResponse.java
  src/main/java/com/cupid/jikting/like/service/LikeService.java
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
  src/test/java/com/cupid/jikting/like/service/LikeServiceTest.java
Labels: feature, test

#149 [SP-197] 번개팅 참여 기능 구현
  src/main/java/com/cupid/jikting/meeting/controller/InstantMeetingController.java
  src/main/java/com/cupid/jikting/meeting/entity/InstantMeeting.java
  src/main/java/com/cupid/jikting/meeting/entity/InstantMeetingMember.java
  src/main/java/com/cupid/jikting/meeting/service/InstantMeetingService.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/test/java/com/cupid/jikting/meeting/controller/InstantMeetingControllerTest.java
  src/test/java/com/cupid/jikting/meeting/service/InstantMeetingServiceTest.java
Labels: feature, test

#154 [SP-248] jenkins 환경변수 설정
  src/main/resources/application.properties
Labels: release

#156 [SP-272] jwt token 환경변수 설정 적용 안되는 에러 해결
  src/main/resources/application.properties
Labels: hotfix

#157 [SP-200] 회원 프로필 이미지 수정 기능 구현
  build.gradle
  src/main/java/com/cupid/jikting/common/config/S3Config.java
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/common/error/FileUploadException.java
  src/main/java/com/cupid/jikting/member/controller/FileUploadController.java
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
  src/main/resources/application.properties
Labels: feature

#162 [SP-175] 전화번호 인증번호 발급 기능 구현
  build.gradle
  src/main/java/com/cupid/jikting/common/config/RedisConfig.java
  src/main/java/com/cupid/jikting/common/config/RestTemplateConfig.java
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/common/error/SmsSendFailException.java
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
  src/main/java/com/cupid/jikting/common/util/PasswordGenerator.java
  src/main/java/com/cupid/jikting/common/util/VerificationCodeGenerator.java
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/like/dto/MemberProfileResponse.java
  src/main/java/com/cupid/jikting/meeting/entity/InstantMeetingMember.java
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/dto/SignUpVerificationCodeRequest.java
  src/main/java/com/cupid/jikting/member/dto/SmsRequest.java
  src/main/java/com/cupid/jikting/member/dto/SmsResponse.java
  src/main/java/com/cupid/jikting/member/oauth2/CustomOAuth2User.java
  src/main/java/com/cupid/jikting/member/service/CustomOAuth2UserService.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/main/java/com/cupid/jikting/member/service/NCPSmsService.java
  src/main/java/com/cupid/jikting/member/service/SmsService.java
  src/main/resources/application.properties
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
Labels: feature

#164 [SP-238] JaCoCo 적용
  build.gradle
Labels: test

#165 [SP-176] 전화번호 인증번호 확인 기능 구현
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/dto/PhoneVerificationRequest.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature, test

#168 [SP-241] SecurityConfig - API 명세서 권한 배제 URI 추가
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
Labels: fix

#172 [SP-302] api uri 수정 및 cors 허용범위 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/resources/application.properties
  src/test/java/com/cupid/jikting/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
  src/test/java/com/cupid/jikting/meeting/controller/InstantMeetingControllerTest.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/recommend/controller/RecommendControllerTest.java
  src/test/java/com/cupid/jikting/team/controller/TeamControllerTest.java
Labels: hotfix

#175 [SP-280] API 명세서 미생성 에러 수정
  build.gradle
Labels: release, hotfix

#170 [SP-276] jwt access token 예외처리
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/common/filter/ExceptionHandlerFilter.java
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/jwt/service/JwtService.java
Labels: feature

#177 [SP-242] 토큰 처리 어노테이션 적용
  src/main/java/com/cupid/jikting/chatting/controller/ChattingRoomController.java
  src/main/java/com/cupid/jikting/chatting/service/ChattingRoomService.java
  src/main/java/com/cupid/jikting/common/config/AuthorizationConfig.java
  src/main/java/com/cupid/jikting/common/resolver/AuthorizationResolver.java
  src/main/java/com/cupid/jikting/common/support/AuthorizedVariable.java
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/like/controller/LikeController.java
  src/main/java/com/cupid/jikting/meeting/controller/InstantMeetingController.java
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/recommend/controller/RecommendController.java
  src/main/java/com/cupid/jikting/team/controller/TeamController.java
  src/main/resources/application.properties
  src/test/java/com/cupid/jikting/chatting/service/ChattingRoomServiceTest.java
  src/test/java/com/cupid/jikting/recommend/service/RecommendServiceTest.java
Labels: feature, fix

#183 [SP-249] TeamMember 생성 패턴 수정
  src/main/java/com/cupid/jikting/team/entity/TeamMember.java
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
  src/test/java/com/cupid/jikting/like/service/LikeServiceTest.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: refactor

#185 [SP-275] 이미지 등록 로직 리팩토링
  src/main/java/com/cupid/jikting/chatting/controller/ChattingRoomController.java
  src/main/java/com/cupid/jikting/like/controller/LikeController.java
  src/main/java/com/cupid/jikting/meeting/controller/InstantMeetingController.java
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/handler/LoginFailureHandler.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/main/java/com/cupid/jikting/recommend/controller/RecommendController.java
  src/main/java/com/cupid/jikting/team/controller/TeamController.java
  src/test/java/com/cupid/jikting/member/controller/FileUploadControllerTest.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
Labels: refactor

#187 [SP-283] 호감 보내기 구현
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/recommend/repository/RecommendRepository.java
  src/main/java/com/cupid/jikting/recommend/service/RecommendService.java
  src/test/java/com/cupid/jikting/recommend/service/RecommendServiceTest.java
Labels: feature, test

#189 [SP-305] security config JwtAuthenticationProcessFilter redisConnect 주입 삭제
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/member/repository/MemberRepository.java
Labels: hotfix

#191 [SP-303] Oauth2 에러 해결
  build.gradle
  src/main/java/com/cupid/jikting/common/config/RedisConfig.java
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/jwt/service/JwtService.java
  src/main/java/com/cupid/jikting/member/handler/OAuth2LoginSuccessHandler.java
  src/main/resources/application.properties
Labels: fix

#195 [SP-304] 추천 목록 응답 DTO 팀 이름 및 소개 추가
  src/main/java/com/cupid/jikting/recommend/dto/RecommendResponse.java
  src/main/java/com/cupid/jikting/recommend/entity/Recommend.java
  src/test/java/com/cupid/jikting/recommend/controller/RecommendControllerTest.java
Labels: fix

#196 [SP-306] SQLDelete 어노테이션 sql문 수정
  src/main/java/com/cupid/jikting/chatting/entity/ChattingRoom.java
  src/main/java/com/cupid/jikting/chatting/entity/MemberChattingRoom.java
  src/main/java/com/cupid/jikting/common/entity/BaseEntity.java
Labels: fix

#199 [SP-338] 회원 관련 요청 토큰 처리 로직 추가
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
Labels: fix

#202 [SP-311] 채팅방 입장 API 구현
  src/main/java/com/cupid/jikting/chatting/config/WebSocketConfig.java
  src/main/java/com/cupid/jikting/chatting/controller/ChattingController.java
  src/main/java/com/cupid/jikting/chatting/controller/ChattingRoomController.java
  src/main/java/com/cupid/jikting/chatting/dto/ChattingRequest.java
  src/main/java/com/cupid/jikting/chatting/dto/ChattingResponse.java
  src/main/java/com/cupid/jikting/chatting/dto/ChattingRoomDetailResponse.java
  src/main/java/com/cupid/jikting/chatting/dto/MemberResponse.java
  src/main/java/com/cupid/jikting/chatting/entity/Chatting.java
  src/main/java/com/cupid/jikting/chatting/entity/ChattingRoom.java
  src/main/java/com/cupid/jikting/chatting/service/ChattingRoomService.java
  src/main/java/com/cupid/jikting/chatting/service/RedisSubscriber.java
  src/main/java/com/cupid/jikting/common/config/RedisConfig.java
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
  src/main/java/com/cupid/jikting/meeting/entity/Meeting.java
  src/test/java/com/cupid/jikting/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/cupid/jikting/chatting/service/ChattingRoomServiceTest.java
  src/test/java/com/cupid/jikting/recommend/controller/RecommendControllerTest.java
Labels: feature

#204 [SP-332] 채팅 목록 조회 API 수정
  src/main/java/com/cupid/jikting/chatting/config/WebSocketConfig.java
  src/main/java/com/cupid/jikting/chatting/entity/ChattingRoom.java
  src/main/java/com/cupid/jikting/chatting/service/ChattingRoomService.java
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/meeting/entity/Meeting.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/test/java/com/cupid/jikting/chatting/service/ChattingRoomServiceTest.java
Labels: fix

#209 [SP-330] 회원가입 url 미허용 hotfix
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: hotfix

#211 [SP-331] 팀 정보 조회 api 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/cupid/jikting/member/dto/MemberProfileUpdateRequest.java
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/main/java/com/cupid/jikting/team/controller/TeamController.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/cupid/jikting/chatting/service/ChattingRoomServiceTest.java
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
  src/test/java/com/cupid/jikting/like/service/LikeServiceTest.java
  src/test/java/com/cupid/jikting/meeting/service/InstantMeetingServiceTest.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
  src/test/java/com/cupid/jikting/recommend/controller/RecommendControllerTest.java
  src/test/java/com/cupid/jikting/team/controller/TeamControllerTest.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: fix

#213 [SP-353] 로그인 시 멤버 PK 반환 로직 추가
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/member/handler/LoginSuccessHandler.java
Labels: feature

#215 [SP-342] S3 저장 이미지 파일명 UUID로 수정
  src/main/java/com/cupid/jikting/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
Labels: fix

#219 [SP-359] Redis 채팅 클래스 캐스팅 에러 해결
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
Labels: hotfix

#220 [SP-359] Redis 채팅 클래스 캐스팅 에러 해결
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
  src/main/java/com/cupid/jikting/common/util/JsonParser.java
Labels: hotfix

#221 [SP-359] Redis 채팅 클래스 캐스팅 에러 해결
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
  src/main/java/com/cupid/jikting/common/util/JsonParser.java
Labels: hotfix

#223 [SP-361] 호감 목록 조회 DTO 팀 소개 필드 추가
  src/main/java/com/cupid/jikting/like/dto/LikeResponse.java
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
Labels: fix

#227 [SP-363] Soft Delete 누락된 Where 절 추가
  src/main/java/com/cupid/jikting/chatting/entity/ChattingRoom.java
  src/main/java/com/cupid/jikting/chatting/entity/MemberChattingRoom.java
Labels: hotfix

#229 [SP-364] 채팅 목록 DTO 최신 메시지 수정
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
Labels: fix

#231 [SP-367] 팀 등록 에러 수정
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/main/java/com/cupid/jikting/team/entity/Team.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: fix

#233 [SP-366] 서버 TIMEZONE 설정 수정
  Dockerfile
Labels: fix

#237 [SP-357] 팀원 삭제 memberId -> memberProileId로 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/main/java/com/cupid/jikting/recommend/dto/ImageResponse.java
  src/main/java/com/cupid/jikting/team/controller/TeamController.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
Labels: refactor

#239 [SP-355] Team 엔티티 성별 필드 추가
  src/main/java/com/cupid/jikting/team/entity/Team.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/repository/TeamRepositoryTest.java
Labels: feature
