Repository SWM-Cupid/jikting-backend, pull requests merged in 2023-09, with the labels that each got.

#248 [SP-408] 회원 프로필 수정 파일 null 허용 설정 추가
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
Labels: fix

#241 [SP-277] logout 처리 구현
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/common/filter/ExceptionHandlerFilter.java
  src/main/java/com/cupid/jikting/common/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/cupid/jikting/common/jwt/service/JwtService.java
  src/main/java/com/cupid/jikting/common/repository/JwtRepository.java
  src/main/java/com/cupid/jikting/common/resolver/AuthorizationResolver.java
  src/main/java/com/cupid/jikting/common/service/RedisConnector.java
  src/main/java/com/cupid/jikting/jwt/service/JwtService.java
  src/main/java/com/cupid/jikting/member/handler/CustomLogoutHandler.java
  src/main/java/com/cupid/jikting/member/handler/LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/service/CustomOAuth2UserService.java
  src/main/resources/application.properties
  src/test/java/com/cupid/jikting/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
  src/test/java/com/cupid/jikting/meeting/controller/InstantMeetingControllerTest.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/recommend/controller/RecommendControllerTest.java
  src/test/java/com/cupid/jikting/team/controller/TeamControllerTest.java
Labels: feature

#251 [SP-409] 회원 프로필 수정 파일 null 체크 로직 수정
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: hotfix

#245 [SP-391] 같은 회사 차단 api 명세서 작성
  src/docs/asciidoc/index.adoc
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/entity/MemberCompany.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
Labels: feature, test

#254 [SP-377] 로그인 응답값 ROLE 추가
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/member/dto/LoginResponse.java
  src/main/java/com/cupid/jikting/member/entity/SocialType.java
  src/main/java/com/cupid/jikting/member/handler/LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
Labels: feature, fix

#257 [SP-411] JwtAuthenticationProcessingFilter 소션 로그인 패스워드 생성 에러 해결
  src/main/java/com/cupid/jikting/common/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: hotfix

#252 [SP-243] 팀명 자동 생성기 제작
  src/main/java/com/cupid/jikting/common/util/PasswordGenerator.java
  src/main/java/com/cupid/jikting/common/util/RandomGenerator.java
  src/main/java/com/cupid/jikting/common/util/TeamNameGenerator.java
  src/main/java/com/cupid/jikting/common/util/VerificationCodeGenerator.java
  src/main/java/com/cupid/jikting/team/repository/TeamRepository.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
Labels: feature

#259 [SP-381] 이미지 업로드 제한 크기 수정
  src/main/resources/application.properties
Labels: fix

#255 [SP-373] 아이디 찾기 인증번호 인증 API 추가
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/member/dto/UsernameResponse.java
  src/main/java/com/cupid/jikting/member/dto/VerificationRequest.java
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/repository/MemberRepository.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/repository/MemberRepositoryTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#262 [SP-374] 비밀번호 재설정 인증번호 발급 API 추가
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/repository/MemberRepository.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/repository/MemberRepositoryTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#264 [SP-375] 비밀번호 재설정 인증번호 인증 API 추가
  src/main/java/com/cupid/jikting/member/dto/SendSmsRequest.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/main/java/com/cupid/jikting/member/service/NCPSmsService.java
  src/main/java/com/cupid/jikting/member/service/SmsService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#266 [SP-376] 비밀번호 재설정 API 추가
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#269 [SP-407] 마이페이지 프로필 조회 응답 DTO 수정
  src/main/java/com/cupid/jikting/member/dto/MemberProfileResponse.java
  src/test/java/com/cupid/jikting/chatting/service/ChattingRoomServiceTest.java
  src/test/java/com/cupid/jikting/like/service/LikeServiceTest.java
  src/test/java/com/cupid/jikting/meeting/service/InstantMeetingServiceTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
  src/test/java/com/cupid/jikting/recommend/service/RecommendServiceTest.java
  src/test/java/com/cupid/jikting/team/repository/TeamRepositoryTest.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: fix, refactor, test

#267 [SP-393] 같은 회사 추천 제외 api 구현
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/entity/MemberCompany.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature, test

#272 [SP-387] 카카오 로그인 추가 정보 받아오기
  src/main/java/com/cupid/jikting/member/oauth2/OAuthAttributes.java
  src/main/java/com/cupid/jikting/member/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/cupid/jikting/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/cupid/jikting/member/oauth2/userinfo/OAuth2UserInfo.java
Labels: feature

#275 [SP-412] TeamPersonalities 엔티티 리스트 고아객체 설정 추가
  src/main/java/com/cupid/jikting/team/entity/TeamPersonalities.java
Labels: fix
