Repository SWM-Cupid/jikting-backend, pull requests merged in 2023-10, with the labels that each got.

#279 [SP-406] 추천 응답 DTO 사용자 이미지 memberProfileId 필드 삭제
  src/main/java/com/cupid/jikting/recommend/dto/ImageResponse.java
Labels: fix

#277 [SP-384] Controller 로깅 구현
  build.gradle
  src/main/java/com/cupid/jikting/chatting/dto/ChattingRequest.java
  src/main/java/com/cupid/jikting/chatting/dto/MeetingConfirmRequest.java
  src/main/java/com/cupid/jikting/common/aop/LogAspect.java
  src/main/java/com/cupid/jikting/member/dto/CompanyVerificationCodeRequest.java
  src/main/java/com/cupid/jikting/member/dto/CompanyVerificationRequest.java
  src/main/java/com/cupid/jikting/member/dto/ImageRequest.java
  src/main/java/com/cupid/jikting/member/dto/LoginRequest.java
  src/main/java/com/cupid/jikting/member/dto/MemberProfileUpdateRequest.java
  src/main/java/com/cupid/jikting/member/dto/NicknameCheckRequest.java
  src/main/java/com/cupid/jikting/member/dto/NicknameUpdateRequest.java
  src/main/java/com/cupid/jikting/member/dto/PasswordResetRequest.java
  src/main/java/com/cupid/jikting/member/dto/PasswordResetVerificationCodeRequest.java
  src/main/java/com/cupid/jikting/member/dto/PasswordUpdateRequest.java
  src/main/java/com/cupid/jikting/member/dto/PhoneVerificationRequest.java
  src/main/java/com/cupid/jikting/member/dto/SendSmsRequest.java
  src/main/java/com/cupid/jikting/member/dto/SignUpVerificationCodeRequest.java
  src/main/java/com/cupid/jikting/member/dto/SignupRequest.java
  src/main/java/com/cupid/jikting/member/dto/SmsRequest.java
  src/main/java/com/cupid/jikting/member/dto/UsernameCheckRequest.java
  src/main/java/com/cupid/jikting/member/dto/UsernameSearchVerificationCodeRequest.java
  src/main/java/com/cupid/jikting/member/dto/VerificationRequest.java
  src/main/java/com/cupid/jikting/member/dto/WithdrawRequest.java
  src/main/java/com/cupid/jikting/team/dto/TeamRegisterRequest.java
  src/main/java/com/cupid/jikting/team/dto/TeamUpdateRequest.java
Labels: feature

#282 [SP-414] 회사 이메일 인증번호 인증 기능 구현
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/dto/VerificationEmailRequest.java
  src/main/java/com/cupid/jikting/member/dto/VerificationPhoneRequest.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#285 [SP-415] Security 비밀번호 재설정 인증 요청 허용
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/test/java/com/cupid/jikting/meeting/service/InstantMeetingServiceTest.java
Labels: hotfix

#283 [SP-235] AWS Rekognition 얼굴 인식 추가
  build.gradle
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
Labels: feature

#287 [SP-416] Security 비밀번호 재설정 요청 허용
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
Labels: hotfix
