Repository SWM-Cupid/jikting-backend, pull requests merged in 2023-11, with the labels that each got.

#290 [SP-421] 회원가입 API 가입된 전화번호 차단 기능 추가
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/member/repository/MemberRepository.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#292 [SP-420] 이미지 파일 확장자 제한 추가
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
Labels: fix

#294 [SP-422] MemberControllerTest Multipart 요청 테스트 리팩토링
  src/test/java/com/cupid/jikting/like/controller/LikeControllerTest.java
  src/test/java/com/cupid/jikting/meeting/controller/InstantMeetingControllerTest.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/recommend/controller/RecommendControllerTest.java
  src/test/java/com/cupid/jikting/team/controller/TeamControllerTest.java
Labels: refactor

#296 [SP-423] 회사 이메일 인증 API 명세서 수정
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
Labels: docs, fix

#298 [SP-379] 사용자 신고 api 명세서 작성
  src/docs/asciidoc/index.adoc
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/dto/ReportMessageRequest.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
Labels: feature, test

#300 [SP-380] 사용자 신고 API 작성
  src/main/java/com/cupid/jikting/member/entity/Report.java
  src/main/java/com/cupid/jikting/member/repository/ReportRepository.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#302 [SP-428] 회원가입 API 응답 토큰 추가
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/dto/LoginResponse.java
  src/main/java/com/cupid/jikting/member/handler/LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
Labels: feature

#304 [SP-429] 회원 프로필 기본값 추가
  src/main/java/com/cupid/jikting/member/dto/MemberProfileResponse.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: feature

#308 [SP-432] 팀 등록 API 응답값 수정
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/main/java/com/cupid/jikting/team/controller/TeamController.java
  src/main/java/com/cupid/jikting/team/dto/TeamRegisterResponse.java
  src/main/java/com/cupid/jikting/team/dto/TeamResponse.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/controller/TeamControllerTest.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: fix

#310 [SP-433] 회원 프로필 수정 로직 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/cupid/jikting/common/config/SecurityConfig.java
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/entity/MemberProfile.java
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: hotfix

#312 [SP-434] Rekognition 주석해제
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
Labels: hotfix

#314 [SP-435] 회사 이메일 인증 로직 수정
  src/main/java/com/cupid/jikting/member/controller/MemberController.java
  src/main/java/com/cupid/jikting/member/entity/Company.java
  src/main/java/com/cupid/jikting/member/entity/Member.java
  src/main/java/com/cupid/jikting/member/entity/MemberCompany.java
  src/main/java/com/cupid/jikting/member/repository/CompanyRepository.java
  src/main/java/com/cupid/jikting/member/service/MemberService.java
  src/test/java/com/cupid/jikting/member/controller/MemberControllerTest.java
  src/test/java/com/cupid/jikting/member/service/MemberServiceTest.java
Labels: fix

#316 [SP-436] 팀 등록 시 회사 미인증 사용자 제한 로직 추가
  src/main/java/com/cupid/jikting/common/error/ApplicationError.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: feature

#318 [SP-437] 팀 참여 시 이미 팀 있는 사용자 제한 로직 추가
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: feature

#320 [SP-438] 사진 업로드 jpg 확장자 추가
  build.gradle
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
Labels: hotfix

#322 [SP-439] fix: AWS Rekognition 액세스 키 추가
  build.gradle
  src/main/java/com/cupid/jikting/member/service/FileUploadService.java
Labels: hotfix

#326 [SP-442] 팀 등록 시 팀 구성 완료 여부 확인 로직 수정
  src/main/java/com/cupid/jikting/team/entity/Team.java
  src/main/java/com/cupid/jikting/team/repository/CustomTeamRepository.java
  src/main/java/com/cupid/jikting/team/repository/CustomTeamRepositoryImpl.java
  src/main/java/com/cupid/jikting/team/service/TeamService.java
  src/test/java/com/cupid/jikting/team/service/TeamServiceTest.java
Labels: hotfix

#328 [SP-443] 레포지토리 테스트 삭제
  src/test/java/com/cupid/jikting/common/repository/PersonalityRepositoryTest.java
  src/test/java/com/cupid/jikting/member/repository/HobbyRepositoryTest.java
  src/test/java/com/cupid/jikting/member/repository/MemberRepositoryTest.java
  src/test/java/com/cupid/jikting/team/repository/TeamRepositoryTest.java
Labels: hotfix
